SELECT * FROM SUSUUS WHERE SUSUUSNM LIKE  '%ORTIZ%'

CREATE VIEW PRUEBA AS 
SELECT A.SUSUUSID AS ID, SUSUUSNM AS NOMBRE, SUSUUSEMAIL AS CORREO,PNTDSC AS ACCION  FROM SUSUUS AS A  JOIN SUSULGP AS B ON A.SUSUUSID= B.SUSUUSID

SELECT * FROM PRUEBA

DROP VIEW PRUEBA